apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: yildirim7mustafa/fastapi  # 🔹 Docker Hub veya local registry için uygun bir image ismi kullan
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/postgres"  # 🔹 Servis adı kullanıldı
---
apiVersion: v1
kind: Service
metadata:
  #name: fastapi-service
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort  # 🔹 Eğer cluster dışına açmak istersen LoadBalancer veya NodePort kullan
