apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi  # 🔹 1GB disk alanı ayırdık
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 🔹 Silinse bile veriyi sakla
  hostPath:
    path: "/mnt/data/postgres"  # 🔹 Minikube veya Bare Metal'de kullanılacak path